config/routes.rb
OnRuby::Application.routes.draw do

  ActiveAdmin.routes(self)
  # make the logout of rails-admin functional
  match '/admin/logout', to: 'sessions#destroy', as: :destroy_admin_user_session

  resources :users
  resources :locations

  # legacy urls
  match '/events/rss', to: 'events#index', defaults: {format: :xml}

  resources :events do
    post 'add_user',  on: :member
    resources :materials
    resources :topics
    resources :participants
  end

  resources :topics do
    resources :likes
  end
  match 'wishes/:slug' => redirect('/topics/%{slug}')

  scope '/auth' do
    get '/:provider/callback',       to: 'sessions#create'
    get '/failure',                  to: 'sessions#failure'
    get '/destroy_user_session',     to: 'sessions#destroy_user_session', as: :destroy_user_session
    get '/destroy_session',          to: 'sessions#destroy',              as: :destroy_session
    get '/login/:provider',          to: 'sessions#auth',                 as: :auth,                 defaults: { provider: 'twitter' }
    get '/offline_login/:nickname',  to: 'sessions#offline_login' if Rails.env.development?
  end

  match '/trigger_error',   to: 'misc#trigger_error'

  match '/home/labels',     to: 'home#labels',    as: :labels
  match '/home/settings',   to: 'home#settings',  as: :settings
  match '/sitemap/:label',  to: 'misc#sitemap',   as: :sitemap, format: :xml
  match '/api',             to: 'api#index'

  root to: "home#index"

  match '/*tail' => redirect("/home/labels")
end

app/views/mobile/layouts/_header.slim
div data-role="header"
  h3= mobile_title
  = link_to t('mobile.home'), labels_url(subdomain: false), data: {icon: :home, iconpos: :notext}
  = link_to t('mobile.settings'), settings_path, data: {icon: :gear, iconpos: :notext}
- flash.each do |name, msg|
  = content_tag :div, msg, id: "flash_#{name}", class: "ui-body"

app/views/mobile/layouts/application.slim
doctype 5
html
  head
    title= mobile_title
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = browser_icon
    = touch_icon
    = csrf_meta_tag
    = stylesheet_link_tag "mobile"
    = javascript_include_tag "mobile"
  body
    div data-role="page" data-theme="a" data-content-theme="a"
      = render 'layouts/header'
      div data-role="content"
        = yield
        = render 'shared/script'