config/routes.rb
OnRuby::Application.routes.draw do

  ActiveAdmin.routes(self)
  # make the logout of rails-admin functional
  match '/admin/logout', to: 'sessions#destroy', as: :destroy_admin_user_session

  resources :users
  resources :locations

  # legacy urls
  match '/events/rss', to: 'events#index', defaults: {format: :xml}

  resources :events do
    post 'add_user',  on: :member
    resources :materials
    resources :topics
    resources :participants
  end

  resources :topics do
    resources :likes
  end
  match 'wishes/:slug' => redirect('/topics/%{slug}')

  scope '/auth' do
    get '/:provider/callback',       to: 'sessions#create'
    get '/failure',                  to: 'sessions#failure'
    get '/destroy_user_session',     to: 'sessions#destroy_user_session', as: :destroy_user_session
    get '/destroy_session',          to: 'sessions#destroy',              as: :destroy_session
    get '/login/:provider',          to: 'sessions#auth',                 as: :auth,                 defaults: { provider: 'twitter' }
    get '/offline_login/:nickname',  to: 'sessions#offline_login' if Rails.env.development?
  end

  match '/trigger_error',   to: 'misc#trigger_error'

  match '/home/labels',     to: 'home#labels',    as: :labels
  match '/home/settings',   to: 'home#settings',  as: :settings
  match '/sitemap/:label',  to: 'misc#sitemap',   as: :sitemap, format: :xml
  match '/api',             to: 'api#index'

  root to: "home#index"

  match '/*tail' => redirect("/home/labels")
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  acts_as_api

  api_accessible :ios_v1 do |template|
    template.add :id
    template.add :event_id
    template.add :user_id
    template.add :name
    template.add :description
  end

  validates :user, :name, :description, :label, presence: true
  validates :name, uniqueness: true

  attr_accessible :label, :name, :user, :description
  attr_accessible :label, :name, :event, :event_id, :user, :user_id, :description, as: :admin

  belongs_to :user
  belongs_to :event

  has_many :likes, dependent: :destroy

  scope :ordered, order('created_at DESC')
  scope :undone, where('event_id IS NULL')
  scope :done, where('event_id IS NOT NULL')

  default_scope -> { where(label: Whitelabel[:label_id]) }

  def already_liked?(user)
    likes.detect{ |like| like.user == user }
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :check_login, only: [:new, :create, :edit, :update]

  expose(:topic)
  expose(:undone_topics) { Topic.ordered.undone }
  expose(:done_topics) { Topic.ordered.done }

  def show; end
  def new; end
  def edit; end

  def create
    topic.label = Whitelabel[:label_id]
    topic.user  = current_user
    if topic.save
      redirect_to(topic_path(topic), notice: t("flash.topic_added"))
    else
      redirect_to(new_topic_path, alert: topic.errors.full_messages.join(', '))
    end
  end

  def update
    if topic.user == current_user
      if topic.save
        redirect_to(topic_path(topic), notice: t("flash.topic_updated"))
      else
        redirect_to(edit_topic_path, alert: topic.errors.full_messages.join(', '))
      end
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def like_link(topic)
    if signed_in?
      if topic.user == current_user
        button_to t('topic.edit'), edit_topic_path(topic), method: :get
      elsif like = topic.already_liked?(current_user)
        button_to t('topic.unlike'), topic_like_path(like.topic, like), method: :delete
      else
        button_to t('topic.like'), topic_likes_path(topic), method: :post
      end
    else
      button_to t('topic.like'), '', data: { disable: t('show.login_before_attend') }
    end
  end
end

app/views/topics/_done.slim
- if topics.present?
  #done
    h3= link_to_unless current_page?(controller: :topics), t('home.old_topics'), topics_path

    ul.more-list.clearfix
      - topics.each do |topic|
        li.topic= link_to_topic topic

app/views/topics/_form.slim
= semantic_form_for topic do |f|
  = f.input :name
  = f.input :description
  = f.action :submit

app/views/topics/_like.slim
- if signed_in?
  .like_count
    = "+"
    span.num= "#{topic.likes.count}"
  - if topic.already_liked?(current_user)
    .like.liked
      .like_text like
  - else
    .like= link_to topic_likes_path(topic), method: :post, remote: true do
      .like_text like

app/views/topics/_likes.slim
- if topic.likes.present?
  h3= t 'topic.likes', count: topic.likes.size
  ul
    - topic.likes.each do |like|
      li.like= link_to_user like.user

app/views/topics/_undone.slim
- if topics.present?
  #undone
    h3= t("home.new_topics")
    ul.more-list.undone.clearfix
      - topics.each do |topic|
        li.topic= link_to_topic topic

app/views/topics/edit.slim
= section_box :topics do
  p.info== t("topic.markdown")
  p= render 'form', topic: topic
  = render 'undone', topics: undone_topics

app/views/topics/index.slim
= section_box :topics do
  = render 'done', topics: done_topics

app/views/topics/new.slim
= section_box :topics do
  p.info== t("topic.markdown")
  p= render 'form', topic: topic
  = render 'undone', topics: undone_topics

app/views/topics/show.html.slim
section
  = likes
  h2= topic.name

  == markdown topic.description

  - if topic.likes.present?
    h3= t 'topic.likes', count: topic.likes.size
    ul
      - topic.likes.each do |like|
        li
          .like
            .like_text like
          = link_to_user like.user

app/views/topics/show.mobile.slim
h2= topic.name

== markdown topic.description

app/views/topics/show.slim
section
  = likes
  h2= topic.name
  .participation= like_link(topic)
  p.meta
    == t 'topic.created_by_user', user: link_to_user(topic.user)
  p.meta
    - if event = topic.event
      == t "topic.hosted_by", host: link_to_user(event.user), event: link_to_event(event)
    - else
      = t 'topic.no_event'


  == markdown topic.description

  = render 'likes', likes: topic.likes