config/routes.rb
OnRuby::Application.routes.draw do

  ActiveAdmin.routes(self)
  # make the logout of rails-admin functional
  match '/admin/logout', to: 'sessions#destroy', as: :destroy_admin_user_session

  resources :users
  resources :locations

  # legacy urls
  match '/events/rss', to: 'events#index', defaults: {format: :xml}

  resources :events do
    post 'add_user',  on: :member
    resources :materials
    resources :topics
    resources :participants
  end

  resources :topics do
    resources :likes
  end
  match 'wishes/:slug' => redirect('/topics/%{slug}')

  scope '/auth' do
    get '/:provider/callback',       to: 'sessions#create'
    get '/failure',                  to: 'sessions#failure'
    get '/destroy_user_session',     to: 'sessions#destroy_user_session', as: :destroy_user_session
    get '/destroy_session',          to: 'sessions#destroy',              as: :destroy_session
    get '/login/:provider',          to: 'sessions#auth',                 as: :auth,                 defaults: { provider: 'twitter' }
    get '/offline_login/:nickname',  to: 'sessions#offline_login' if Rails.env.development?
  end

  match '/trigger_error',   to: 'misc#trigger_error'

  match '/home/labels',     to: 'home#labels',    as: :labels
  match '/home/settings',   to: 'home#settings',  as: :settings
  match '/sitemap/:label',  to: 'misc#sitemap',   as: :sitemap, format: :xml
  match '/api',             to: 'api#index'

  root to: "home#index"

  match '/*tail' => redirect("/home/labels")
end

app/views/shared/_footer.html.slim
section.clearfix
  .info.clearfix.hr
    .contact.block
      h2= t("footer.contact")
      ul
        li
          = link_to_twitter Whitelabel[:twitter] do
            = "Twitter"
        li= mail_to Whitelabel[:email], 'E-Mail', title: 'E-Mail'

    .links.block
      h2= t("footer.links")
      ul
        li= link_to 'GitHub', 'http://github.com/phoet/on_ruby', title: 'Fork me on GitHub'
        li= link_to 'Mailinglist', (Whitelabel[:mailing_list] || 'https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-ug-germany'), title: 'Mailinglist'
        li= link_to t("footer.to_mobile"), root_path(mobile: 1)

    .imprint.block
      h2= t("footer.imprint")
      ul
        li== imprint[:contributors].map { |c| mail_to c[:email], c[:name], title: c[:name] }.join(' ')
        - if imprint[:address]
          li== imprint[:address].gsub("\n", "<br/>")

  - if other_usergroups.present?
    .usergroups.block.hr
      h2= t("footer.other_usergroups")
      ol.clearfix
        - other_usergroups.each do |ug|
          li
            =' link_to ug[:name], ug[:url], title: ug[:name]
            = link_to_twitter(ug[:twitter], clung: true) if ug[:twitter]

  .railsgroups.block
    h2= t("footer.ruby_usergroups")
    ol.clearfix
      - Whitelabel.labels.each do |label|
        li
          - name = t("label.#{label.label_id}.name")
          =' link_to name, root_url(subdomain: label.label_id, domain: HOST), title: name
          = link_to_twitter(label.twitter, clung: true)

app/views/shared/_login.html.slim
#login
  - if signed_in?
    .user= link_to image_tag(current_user.image, alt: current_user.name), user_path(current_user), title: current_user.name
    ul
      li= link_to t("login.profile"), user_path(current_user), title: t("login.profile")
      li= link_to t("login.edit_profile"), edit_user_path(current_user), title: t("login.edit_profile")
      li= link_to t("login.logout"), destroy_session_path(current_user), title: t("login.logout")
  - else
    ul
      - [:twitter, :github].each do |provider|
        - title = t("login.#{provider}_login")
        li.provider= link_to title, auth_path(provider: provider), title: title

app/views/shared/_nav.html.slim
ul
  - [:events, :topics, :people, :locations].each do |it|
    li= link_to t(it), root_path(anchor: it), title: t(it)

#locale
  ul
    -[:de, :en].each do |locale|
      - title = t("switch_languages", language: t("languages.#{locale}"))
      li= link_to image_tag("flags/#{locale}.png", alt: title), url_for(locale: locale), title: title

app/views/shared/_script.slim
- if Rails.env.production?
  javascript:
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-20148095-1']);
    _gaq.push(['_setDomainName', 'onruby.de']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();