config/routes.rb
OnRuby::Application.routes.draw do

  ActiveAdmin.routes(self)
  # make the logout of rails-admin functional
  match '/admin/logout', to: 'sessions#destroy', as: :destroy_admin_user_session

  resources :users
  resources :locations

  # legacy urls
  match '/events/rss', to: 'events#index', defaults: {format: :xml}

  resources :events do
    post 'add_user',  on: :member
    resources :materials
    resources :topics
    resources :participants
  end

  resources :topics do
    resources :likes
  end
  match 'wishes/:slug' => redirect('/topics/%{slug}')

  scope '/auth' do
    get '/:provider/callback',       to: 'sessions#create'
    get '/failure',                  to: 'sessions#failure'
    get '/destroy_user_session',     to: 'sessions#destroy_user_session', as: :destroy_user_session
    get '/destroy_session',          to: 'sessions#destroy',              as: :destroy_session
    get '/login/:provider',          to: 'sessions#auth',                 as: :auth,                 defaults: { provider: 'twitter' }
    get '/offline_login/:nickname',  to: 'sessions#offline_login' if Rails.env.development?
  end

  match '/trigger_error',   to: 'misc#trigger_error'

  match '/home/labels',     to: 'home#labels',    as: :labels
  match '/home/settings',   to: 'home#settings',  as: :settings
  match '/sitemap/:label',  to: 'misc#sitemap',   as: :sitemap, format: :xml
  match '/api',             to: 'api#index'

  root to: "home#index"

  match '/*tail' => redirect("/home/labels")
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose(:current_event) { Event.current.first }
  expose(:events) { Event.latest }
  expose(:people) { User.peers }
  expose(:undone_topics) { Topic.ordered.undone }
  expose(:done_topics) { Topic.ordered.done.limit(10) }
  expose(:organizers) { User.organizers }
  expose(:locations)

  def labels
    render layout: "labels" unless mobile_device?
  end

  def settings; end
end

app/views/home/_events.html.slim
= section_box :events do
  p
    - if current_event
      =' link_to t("home.next_meetup"), current_event, title: current_event.name
      == t("home.takes_place", event_date: content_tag(:em, l(current_event.date)), location_link: link_to(current_event.location.name, current_event.location, title: current_event.location.name))
    - else
      == t("home.next_possible_meetup", event_date: content_tag(:em, l(next_event_date)))
  - if events.any?
    h3= t("home.past_events")
    ul.more-list.clearfix
      - events.each do |event|
        li= link_to "#{l(event.date, format: :date)} - #{event.name}", event_path(event), title: event.name

app/views/home/_people.html.slim
= section_box :people do
  p== t("home.the_usergroup", usergroup: I18n.tw("name"))
  = render 'users/list', users: people

app/views/home/_topics.html.slim
= section_box :topics do
  p
    strong=' t("home.like_to_talk")
    == t("home.send_us_an_email", mail_to: mail_to(Whitelabel[:email], "E-Mail", title: "E-Mail"))
  = render 'users/list', users: organizers
  p== t("home.engage")
  = button_to t("home.add_topic"), new_topic_path, method: :get
  = render 'topics/undone', topics: undone_topics
  = render 'topics/done', topics: done_topics

app/views/home/index.slim
- render_cached do
  = render 'events', events: events, current_event: current_event
  = render 'topics', undone_topics: undone_topics, done_topics: done_topics, organizers: organizers
  = render 'people', people: people
  = render 'locations', locations: locations

app/views/home/labels.slim
section
  ul
    - Whitelabel.labels.each do |label|
      li
        - name = t("label.#{label.label_id}.name")
        = link_to root_url(subdomain: label.label_id), title: name do
          span.image = image_tag("labels/#{label.label_id}.png", alt: name)
          span.host  = name